### ISSUE TITLE
What is the Ang score? 

### ISSUE THREAD

**Issue by BLUENCE** [svip-lab/GazeFollowing#10]
Thank you for your work! 

I wonder which one is the "Angular error".
average loss : [0.05870105 0.1139822  0.17268325]
average error [mean dist, angle, mean angle]: [ 0.14515077 19.66974045 18.10261505]

The Ang is 17.6 on your paper but I got score 18.10 
am I misunderstanding?

**Comment by niujinshuchong** [comment]
@BLUENCE 

The provided model may not exactly the same with the paper because we re-train the model. 
It's normal to have some variation.

**Comment by BLUENCE** [comment]
@niujinshuchong Thank you for your answer!
