### ISSUE TITLE
What is the value of γ ?

### ISSUE THREAD

**Issue by BLUENCE** [svip-lab/GazeFollowing#11]
Hi, I'm just implementing your ablation study.
There are 3 gaze mask fields on your code (gazenet.py). 
γ=1, γ=2, γ=5
**When you train the methods "one-scale", what is the value of γ about the gaze fields?**
because the bigger one is the default setting, I think that γ is 5. but I'm not sure.

**+ Could I know When does Epoch converge?** 

![image](https://user-images.githubusercontent.com/34292395/77046782-f4585880-6a06-11ea-9ea9-589461cedeeb.png)

**Comment by niujinshuchong** [comment]
@BLUENCE 

We set γ=1 for "one-scale" case. See table 1 in the paper.

15 epoch will be enough if I remember correctly.

**Comment by BLUENCE** [comment]
Oh, I misunderstood. The cone becomes narrower as the number increases.
Thank you for your answer.
