### ISSUE TITLE
怎样检测多个人的视线？

### ISSUE THREAD

**Issue by Owen1234560** [svip-lab/GazeFollowing#13]
你好，我看您的预测inference代码，每次检测都要输入人眼的位置，如果同时检测多个人呢，怎么操作？

**Comment by niujinshuchong** [comment]
Hi,

多人的情况需要单独输入每个人对应的人眼位置前向多次。

人眼位置不需要很精确，可以使用人脸检测算法返回的人脸框的中心点作为人眼位置。

**Comment by Owen1234560** [comment]
> Hi,
> 
> 多人的情况需要单独输入每个人对应的人眼位置前向多次。
> 
> 人眼位置不需要很精确，可以使用人脸检测算法返回的人脸框的中心点作为人眼位置。

好的，谢谢。后面可能还有问题请教，再次说声感谢！
