### ISSUE TITLE
人脸位置问题

### ISSUE THREAD

**Issue by Owen1234560** [svip-lab/GazeFollowing#14]
您好，又来请教了。
       在数据处理代码部分,我看到您采用的策略是通过眼部位置剪切出人脸。我见数据集里有人脸位置box数据，您为何不采用？有其他的考虑吗？因为在人脸在每个图片的尺度不同，剪切可能会导致剪切不全或者过多。
       谢谢！
####crop face
        x_c, y_c = eye
        x_0 = x_c - 0.15
        y_0 = y_c - 0.15
        x_1 = x_c + 0.15
        y_1 = y_c + 0.15
        if x_0 < 0:
            x_0 = 0
        if y_0 < 0:
            y_0 = 0
        if x_1 > 1:
            x_1 = 1
        if y_1 > 1:
            y_1 = 1

**Comment by niujinshuchong** [comment]
Hi,

你说的很有道理，直接根据人脸框放大一点剪切出来也是也可以的。

**Comment by Owen1234560** [comment]
> ，直接根据人脸框放大一点剪切出来也是也可以的

好的，谢谢
