### ISSUE TITLE
数据集下载

### ISSUE THREAD

**Issue by Owen1234560** [svip-lab/GazeFollowing#15]
你好，你们自己制作的数据集有没有其他下载方式，onedrive我下载不成功，总是自动暂停。有没有百度网盘呀？谢谢！

**Comment by niujinshuchong** [comment]
@Owen1234560 

很抱歉这么久才回复。 

百度网盘：https://pan.baidu.com/s/1oGb4sQM4xA6GIH0IwZrGDQ
提取码：zalf
