### ISSUE TITLE
头部位置，人眼位置确定

### ISSUE THREAD

**Issue by liuyantingyvonne** [svip-lab/GazeFollowing#16]
您好，看您的论文写的第一部分的输入是人脸图以及头部位置，看您代码inference.py代码里面的输入确实是人脸图还有一个（x, y）坐标，这个坐标指的是头部位置对吗？请问您是如何表示头部位置的呢？是用两只眼睛的中点当头部位置吗？因为您制作了自己的数据集，所以您一定清楚您提取头部位置的数据是如何来的，因为我想用您的模型试着跑一下我自己的数据集，我自己的数据集目前提取了人脸框以及两只眼睛的坐标位置，现在不知道您的头部位置是如何确定的。我尝试用两只眼睛的中点位置当作头部位置，但是人眼视线的位置偏差很大。我跑出来的效果图是这样的，我的数据集的图片大部分都是人脸比较靠近摄像头，我不知道这有没有影响，如果您能尽快帮我解答，我会很感激，麻烦您了！
![image](https://user-images.githubusercontent.com/56375225/92365434-68f29100-f126-11ea-94cd-b384561c5b75.png)

**Comment by niujinshuchong** [comment]
@liuyantingyvonne 
输入坐标是头部中心点在原始图像中的位置。头部的位置可以是人脸包围框的中心。

我觉得我们的模型可能不太适合你这个场景，我们的模型处理的是视点位置在图像内的，而你这个场景更像是使用眼动仪采集的数据。你可以参考一些https://github.com/dongzelian/multi-view-gaze。

**Comment by liuyantingyvonne** [comment]
好的，谢谢您的耐心解答了，确实我的数据集的图片的视点都不在图像内，可能用您这个模型有点勉强了，谢谢您的链接，但是您这个链接失效了，请问你还有其他的链接了，谢谢您了！

**Comment by liuyantingyvonne** [comment]
不好意思，打开链接了，谢谢您！
