### ISSUE TITLE
Eyes coordinates and strange results

### ISSUE THREAD

**Issue by DaddyWesker** [svip-lab/GazeFollowing#18]
Hello and thanks for your code!

I've tried to infer your code on the webcam video and recieved some strange results. After that, i've downloaded several pictures and launched infer on them and have also recieved strange results on couple of them. Here they are. There are also two images from your repo (guy staring at the phone is from the original model's folder and guy on the skate is from your repo). 
![1](https://user-images.githubusercontent.com/10774222/109928265-55d80c80-7cd6-11eb-9e29-816cafe9753d.png)
![2](https://user-images.githubusercontent.com/10774222/109928267-57a1d000-7cd6-11eb-8851-d02fb372f507.png)
![3](https://user-images.githubusercontent.com/10774222/109928275-5a042a00-7cd6-11eb-9200-efe532ead9f6.png)
![4](https://user-images.githubusercontent.com/10774222/109928279-5a9cc080-7cd6-11eb-8aa6-f028b9ec5c20.png)
![5](https://user-images.githubusercontent.com/10774222/109928281-5b355700-7cd6-11eb-9c25-6d4745b09403.png)
![6](https://user-images.githubusercontent.com/10774222/109928286-5b355700-7cd6-11eb-9372-8c3a4bffb77f.png)
![7](https://user-images.githubusercontent.com/10774222/109928291-5c668400-7cd6-11eb-84dc-580789c1b182.png)
![8](https://user-images.githubusercontent.com/10774222/109928292-5cff1a80-7cd6-11eb-8f4b-9dadf7838cf6.png)
![9](https://user-images.githubusercontent.com/10774222/109928296-5cff1a80-7cd6-11eb-80cc-ddb2471c09b6.png)
![10](https://user-images.githubusercontent.com/10774222/109928298-5d97b100-7cd6-11eb-9073-4c41b21cb245.png)
![11](https://user-images.githubusercontent.com/10774222/109928302-5e304780-7cd6-11eb-9998-9f12c5fb818e.png)
![12](https://user-images.githubusercontent.com/10774222/109928305-5e304780-7cd6-11eb-9a46-08c4d20d224a.png)

On some images gaze was detected good, but most of them are quite bad. Could the eye_x and eye_y be the problem? Since, as i understand, it should be different for different images? If so, how to get it?

**Comment by niujinshuchong** [comment]
@DaddyWesker 

Yes. eye_x and eye_y should be different. 

You need to first detect bounding box of the human of interest. I think there are a lot of open source methods for this. Then you can simply use the box center as eye coordinate.

In our implementation, we simply crop a region around eye coordinate as head image. See https://github.com/svip-lab/GazeFollowing/blob/master/code/inference.py#L50

But it would be best to crop the face image with detected bounding box (may also need to scale the box).

**Comment by DaddyWesker** [comment]
Alright, just as i thought. I'll use dlib to detect eyes and will use one of those eyes' center point to put into the model. I'll get back here with the results.

**Comment by DaddyWesker** [comment]
So, i've updated the code with dlib's eye detection and now it works much better. Only problem is whether eyes were detected or not. THanks.

![3](https://user-images.githubusercontent.com/10774222/110079821-a31db200-7d9a-11eb-83ab-43dc678d5715.png)
![4](https://user-images.githubusercontent.com/10774222/110079829-a5800c00-7d9a-11eb-91a4-28cbef07dba2.png)
![5](https://user-images.githubusercontent.com/10774222/110079830-a6b13900-7d9a-11eb-9d56-336d505a5641.png)
![6](https://user-images.githubusercontent.com/10774222/110079833-a7e26600-7d9a-11eb-9afa-c25d97f52d68.png)
![7](https://user-images.githubusercontent.com/10774222/110079838-a9139300-7d9a-11eb-8142-3c11b62229c2.png)
![9](https://user-images.githubusercontent.com/10774222/110079840-a9ac2980-7d9a-11eb-8298-1f98424bfa18.png)
![11](https://user-images.githubusercontent.com/10774222/110079841-aa44c000-7d9a-11eb-9267-939dc121b540.png)
![12](https://user-images.githubusercontent.com/10774222/110079843-aadd5680-7d9a-11eb-8dc4-d46d594351d4.png)

**Comment by pranay-ar** [comment]
Hi @DaddyWesker,

Apologies for a doubt completely unrelated to the title of the issue. I am trying to implement this project on my PC and MIT's webpage for the dataset is down (at least for the test dataset. I downloaded the main dataset but when I extract it, it says that the zip file is corrupted). Since you've implemented this project recently, I just wanted to know if it'll be possible for you to upload and share the datasets over Google Drive/ One Drive. Kindly let me know your thoughts on this. 

Best,
Pranay.

**Comment by DaddyWesker** [comment]
@pranay-ar 
Hello. Unfortunately, i haven't downloaded MIT's datasets. I've just tested this repo with my own images.
