### ISSUE TITLE
../GazeFollowData/test2_annotations.mat

### ISSUE THREAD

**Issue by juzipeel** [svip-lab/GazeFollowing#19]
Hello，You set mat_file='../GazeFollowData/test2_annotations.mat' in the train.py file, but I did not have it in the GazeFollowData data set I downloaded. It is test_annotations_release.txt. I replaced it with a txt file format and it didn’t work. May I ask How to solve it?

**Comment by niujinshuchong** [comment]
@juzipeel It seems that the data format is changed. Maybe you can modified the code here
https://github.com/svip-lab/GazeFollowing/blob/master/code/test_gazefollow.py#L51, which simply load the data.

**Comment by juzipeel** [comment]
The tags of the data set I use are all in txt format. Could you please provide me with the gazefollow data set for your training? If your tags are stored in mat format, thank you very much

**Comment by niujinshuchong** [comment]
@juzipeel 
I just uploaded the test2_annotations.mat
You can download it from
https://github.com/svip-lab/GazeFollowing/blob/master/test2_annotations.mat

**Comment by juzipeel** [comment]
ok，thanks Li dou ***@***.*** 签名由 网易邮箱大师 定制 On 07/06/2021 22:17, niujinshuchong wrote: @juzipeel I just uploaded the test2_annotations.mat You can download it from https://github.com/svip-lab/GazeFollowing/blob/master/test2_annotations.mat — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by juzipeel** [comment]
Could you provide the train_annotations.mat file?

**Comment by dongzelian** [comment]
@juzipeel Hi, we have uploaded the train_annotations.mat file. See https://github.com/svip-lab/GazeFollowing/blob/master/train_annotations.mat.

**Comment by juzipeel** [comment]
Hello, I meet a question when I repeat your data. I know you use OurData/tools/extract_frame.py to extract frame from clipVideo in 2fps and store extracted frames which will be used in OurData/tools/create_video_image_list.py. But what is '--Video_annotation_dir' in create_video_image_list.py in line 11, it seems we didn't gain the path of gaze annatations.

**Comment by niujinshuchong** [comment]
@juzipeel We provided the final processed results (annotation.json). Maybe you don't need to run the preprocess scripts.

**Comment by juzipeel** [comment]
Okay, I just want to know what this means and why I can’t generate the final processed results (annotation.json) when I run it. It always gets a nearly blank file just containing titles ("path","boxes" and "points").

**Comment by juzipeel** [comment]
@niujinshuchong I‘m sorry, but I still want to konw what is '--Video_annotation_dir' in create_video_image_list.py in line 11 and how to configure the path which I didn't gain the path of gaze annotations. I don't expect the final results (annotations.json) you had privided, but just want to repeat.

**Comment by niujinshuchong** [comment]
@juzipeel It seems that we forgot to upload to original annotations. But I cannot find it any more. But create_video_image_list.py simply merge all annotations together to one json file.
