### ISSUE TITLE
What's the point of this if block in train.py?

### ISSUE THREAD

**Issue by mucozcan** [svip-lab/GazeFollowing#20]
Hi, I read your paper and it's a great work! I was viewing your implementation and I couldn't understand this if block in GazeDataset class. What's the point of  `if random.random() > 0.5` and flipping the image : `image = cv2.flip(image, 1)`?

https://github.com/svip-lab/GazeFollowing/blob/d359b6ddd7a172cdbfb80738c564a7e843d3c5d7/code/train.py#L93

**Comment by niujinshuchong** [comment]
@mucozcan It was used for data augmentation.
