### ISSUE TITLE
model accuracy

### ISSUE THREAD

**Issue by Carbord** [svip-lab/GazeFollowing#3]
Hi, I want to know that how this model perform on the Gazefollow Dataset. I train the model only to get the best accuracy --- 0.24 for L2 distance and 34 degree for angular error. But these two metrics is much woreser than those proposed on the paper "Where are they looking", which shows  0.19 for L2 distance and 24 degree for angular error. So I would like know what accuracy did you get while training and testing. And I will be very appreciate if you can share the training parameters for the best accuracy model.

**Comment by dongzelian** [comment]
@Carbord 
Hi, maybe the testing set of the original GazeFollow dataset is not updated, which has wrong labels. You can email authors for new testing data. We also paste the download link provided author when we request.

**Comment by Carbord** [comment]
Thanks a lot, I will try the new test set later~


------------------ 原始邮件 ------------------
发件人: "dongzelian"<notifications@github.com>;
发送时间: 2019年7月4日(星期四) 晚上9:50
收件人: "svip-lab/GazeFollowing"<GazeFollowing@noreply.github.com>;
抄送: "忠平"<1054181675@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [svip-lab/GazeFollowing] model accuracy (#3)




@Carbord
 Hi, maybe the testing set of the original GazeFollow dataset is not updated, which has wrong labels. You can email authors for new testing data. We also paste the download link provided author when we request.
