### ISSUE TITLE
Code visualization problem

### ISSUE THREAD

**Issue by ohMyJason** [svip-lab/GazeFollowing#4]
您好，请问训练完成之后如何导入一个实例，并检测出他的目光呢。我尝试了所有的py文件均无法达到这个目的。
---
Hello, how can I import an instance after the training is completed and detect his gaze? I tried all the py files and could not achieve this.

**Comment by LorraineLQ** [comment]
你好，你提供的gazedata下载后解压失败，数据集无法使用，能麻烦您重新上传一份吗，谢谢！

**Comment by niujinshuchong** [comment]
@LorraineLQ We have downloaded the data and unzip successfully from the provided link. Please try it again.

**Comment by niujinshuchong** [comment]
@ohMyJason Now the system needs an input image with human head bounding box annotation. We will provide sample code for inference on a single image soon.

**Comment by niujinshuchong** [comment]
@ohMyJason Inference code was added. Please refer to https://github.com/svip-lab/GazeFollowing/blob/master/README.md#inference.
