### ISSUE TITLE
how to get the relative coordinates of the gaze on the screen.

### ISSUE THREAD

**Issue by 1158755456** [svip-lab/GazeFollowing#8]
Hello, I have successfully run the information.py file and got the result. But if the figure is looking at the computer screen, how to get the relative coordinates of the gaze on the screen.

**Comment by niujinshuchong** [comment]
Hi, we assume that the person is looking at some point in the image. Therefore, our method do not apply to find the gaze on the screen.

**Comment by 1158755456** [comment]
> 嗨，我们假设这个人正在看图像中的某个点。因此，我们的方法不适用于在屏幕上查找注视。

ok,thank you.
