### ISSUE TITLE
Model evaluation and metrics code

### ISSUE THREAD

**Issue by emannuell** [svip-lab/GazeFollowing#9]
I would like to thank and congratulate for the research work developed and advances achieved.
I have run and implemented my changes on the code, and ow i would like to have the same measures presented in the paper: AUC Dist MDist Ang MAng. In the original code folder there is a text_gazefollow.py file, to evaluate right? After processing the test dataset (GazeFollow dataset recasens 2015) the result was:
```
average loss : [tensor(0.0587, device='cuda:0') tensor(0.1137, device='cuda:0') tensor(0.1724, device='cuda:0')]
average error: [ 0.14532723 19.64980047 18.1135517 ]
```
How can I extract the complete metrics?

Thank you

**Comment by niujinshuchong** [comment]
@emannuell code for other evaluation metrics has uploaded.

Please run
```
python test_gazefollow.py
```
It will save prediction result in the code folder and print mean dist and mean angle (first one and last of average error).

Then you can run 
```
python cal_min_dis.py
python cal_auc.py
```
to get evaluation results.

**Comment by emannuell** [comment]
Does is possible plot ROC curve?

**Comment by emannuell** [comment]
Solution to plot ROC curve and AUC, just copy and paste at end of calc_auc.py file.

`# Compute micro-average ROC curve and ROC area
fpr, tpr, threshold = roc_curve(gt_list, pred_list)
roc_auc = auc(fpr, tpr)

plt.figure()
plt.title('Receiver Operating Characteristic')
plt.plot(fpr, tpr, 'b', label = 'AUC = %0.2f' % roc_auc)
plt.legend(loc = 'lower right')
plt.plot([0, 1], [0, 1],'r--')
plt.xlim([0, 1])
plt.ylim([0, 1])
plt.ylabel('True Positive Rate')
plt.xlabel('False Positive Rate')
plt.show()`

**Comment by emannuell** [comment]
@niujinshuchong how can i have Recases et al. data to plot ROC curve?

**Comment by niujinshuchong** [comment]
@emannuell 

We didn't save the results. But maybe you can run Recases et al. model yourself.
